// flow-typed signature: 65e012758b1d862c43be29eb9a3b4490
// flow-typed version: <<STUB>>/normalize.css_v^8.0.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
